"""LLM-as-a-Judge semantic verifier for RegressionShield SDK.

Supports any OpenAI-compatible provider (OpenRouter, OpenAI, Groq, Ollama, vLLM, DeepSeek).
Allows users to map custom API keys, judge models, and base URLs.
"""

import os
import json
import logging
from typing import Dict, Any, Optional
import httpx

logger = logging.getLogger("regression_shield.llm_judge")


class LLMJudge:
    """Semantic judge auditing agent reasoning and task resolution using an LLM."""

    DEFAULT_MODEL = "minimax/minimax-m2.7:free"
    DEFAULT_BASE_URL = "https://openrouter.ai/api/v1"

    def __init__(
        self,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        timeout: float = 30.0,
    ):
        self.api_key = (
            api_key
            or os.getenv("OPENROUTER_API_KEY")
            or os.getenv("OPENAI_API_KEY")
        )
        self.model = model or os.getenv("JUDGE_MODEL") or self.DEFAULT_MODEL
        self.base_url = (
            base_url
            or os.getenv("OPENROUTER_BASE_URL")
            or os.getenv("OPENAI_BASE_URL")
            or self.DEFAULT_BASE_URL
        ).rstrip("/")
        self.timeout = timeout

    @staticmethod
    def _parse_json_payload(raw_text: str) -> dict:
        """Extract and parse a JSON block from raw LLM output."""
        cleaned = raw_text.strip()
        if "```" in cleaned:
            for part in cleaned.split("```"):
                p_clean = part.strip()
                if p_clean.startswith("json"):
                    p_clean = p_clean[4:].strip()
                if "{" in p_clean and "}" in p_clean:
                    cleaned = p_clean
                    break

        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end != -1:
            cleaned = cleaned[start:end + 1]

        return json.loads(cleaned)

    def verify_reasoning_and_outcome(
        self,
        goal: str,
        trajectory_steps: list,
        final_response: str,
    ) -> Dict[str, Any]:
        """Perform semantic audit on agent reasoning trajectory and final answer.

        Args:
            goal: Original task or goal prompt.
            trajectory_steps: List of executed ReAct steps.
            final_response: Final answer generated by the agent.

        Returns:
            Dict with score (0.0 - 1.0), passed (bool), reasoning, and model.
        """
        if not self.api_key:
            return {
                "score": 1.0,
                "passed": True,
                "reasoning": "LLM Judge skipped: No API key provided (offline deterministic mode).",
                "model": "deterministic_fallback",
            }

        # Build clean execution summary for prompt
        steps_summary = []
        for s in trajectory_steps:
            idx = s.get("step_index", 1)
            thought = s.get("thought", "")
            action = s.get("action", {})
            t_name = action.get("name", "tool")
            t_args = action.get("args") or action.get("arguments") or {}
            obs = s.get("observation", "")
            steps_summary.append(
                f"Step {idx}:\n  Thought: {thought}\n  Action: {t_name}({json.dumps(t_args)})\n  Observation: {str(obs)[:300]}"
            )
        trajectory_text = "\n".join(steps_summary)

        system_instruction = (
            "You are an expert AI Agent Trajectory Judge. Your job is to verify whether the agent's "
            "intermediate reasoning thoughts accurately reflect the tool observations, and whether the "
            "final response correctly satisfies the goal without hallucinating ungrounded data.\n\n"
            "Score from 0.0 to 1.0:\n"
            "1.0 = Flawless reasoning, fully grounded in tool observations, goal achieved.\n"
            "0.5 = Minor reasoning gap or incomplete answer.\n"
            "0.0 = Severe hallucination, claimed success after tool error, or wrong outcome.\n\n"
            "Respond ONLY with a valid JSON block structured like this:\n"
            '{"score": <float between 0.0 and 1.0>, "reasoning": "<concise 1-2 sentence explanation>"}'
        )

        user_content = (
            f"Goal: {goal}\n\n"
            f"Execution Trajectory:\n{trajectory_text}\n\n"
            f"Agent Final Response: {final_response}"
        )

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }

        # Handle OpenRouter vs direct OpenAI URL format
        endpoint = (
            f"{self.base_url}/chat/completions"
            if self.base_url.endswith("/v1")
            else f"{self.base_url}/api/v1/chat/completions"
        )

        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_instruction},
                {"role": "user", "content": user_content},
            ],
            "temperature": 0.0,
        }

        try:
            with httpx.Client(timeout=self.timeout) as client:
                res = client.post(endpoint, headers=headers, json=payload)

            if res.status_code == 200:
                data = res.json()
                content = data["choices"][0]["message"]["content"]
                parsed = self._parse_json_payload(content)
                score = max(0.0, min(1.0, float(parsed.get("score", 1.0))))
                reasoning = str(parsed.get("reasoning", "")).strip()

                return {
                    "score": round(score, 2),
                    "passed": score >= 0.70,
                    "reasoning": reasoning,
                    "model": self.model,
                }
            else:
                logger.warning("LLM Judge HTTP %d: %s", res.status_code, res.text[:120])
                return {
                    "score": 1.0,
                    "passed": True,
                    "reasoning": f"LLM Judge request returned HTTP {res.status_code}. Defaulted to deterministic.",
                    "model": self.model,
                }
        except Exception as err:
            logger.warning("LLM Judge exception: %s", err)
            return {
                "score": 1.0,
                "passed": True,
                "reasoning": f"LLM Judge error ({str(err)}). Defaulted to deterministic.",
                "model": self.model,
            }
